server:
    port: 0
http:
    mappers:
        jsonPrettyPrint: true
spring:
    rabbitmq:
        addresses: node1:5672
        username: guest
        password: guest
        virtual_host: /
    hadoop:
        fsUri: hdfs://node1:8020
        resourceManagerHost: node1
        config:
            topology.script.file.name: /usr/local/hadoops/topology.sh
    yarn:
        appType: BOOT
        appName: gs-yarn-rabbit
        applicationBaseDir: /app/
        applicationDir: /app/gs-yarn-rabbit/
        endpoints:
            containercluster:
                enabled: true
        appmaster:
            appmasterClass: org.springframework.yarn.am.cluster.ManagedContainerClusterAppmaster
            keepContextAlive: true
            containercluster:
                enabled: true
                clusters:
                    producer:
                        projectionType: any
                        projectionAny: 1
                        resource:
                            priority: 1
                            memory: 256
                            virtualCores: 1
                        launchcontext:
                            locality: false
                            archiveFile: gs-yarn-rabbit-cont-producer-0.1.0.jar
                        localizer:
                            patterns:
                                - "*cont-producer*jar"
                    consumer:
                        projectionType: any
                        projectionAny: 1
                        resource:
                            priority: 2
                            memory: 256
                            virtualCores: 1
                        launchcontext:
                            locality: false
                            archiveFile: gs-yarn-rabbit-cont-consumer-0.1.0.jar
                        localizer:
                            patterns:
                                - "*cont-consumer*jar"
